name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node 12
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Install Build Requirements
        run: sudo apt update;
          sudo apt -y upgrade;
          sudo apt install build-essential;
      - name: Debian Build
        working-directory: ${{github.workspace}}/localproxy-server
        run: bash build-deb.sh;
      - name: Upload Ubuntu Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: localproxy_amd64
          path: ${{github.workspace}}/localproxy-server/build/*

      # --- Prep a release for tags ---
      - name: Prepare release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: ${{github.workspace}}/build/packages/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
